services:
  - type: web
    name: shyamconstrudtion
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn shyamconstrudtion.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shyamconstrudtion.settings
