# Generated by Django 5.2.4 on 2025-07-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shyamapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerreview',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='customerreview',
            old_name='comment',
            new_name='review',
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
